# Generated by Django 3.2.4 on 2021-08-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_CBV_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created_data',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='todo/default.jpg', null=True, upload_to='todo/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
