# Generated by Django 3.2.4 on 2021-08-26 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='todo/default.jpg', null=True, upload_to='todo/%Y/%m/%d')),
            ],
        ),
    ]
